<?php

namespace App\Services\RAG;

class FormDataLineageExtractor
{
    /**
     * Extract authoritative knowledge chunks detailing form field and dropdown/select box data lineages
     * across all modules of the Nachias ERP application.
     *
     * @return array<int, array>
     */
    public function extract(): array
    {
        $fields = $this->getLineageDefinitions();
        $chunks = [];

        foreach ($fields as $item) {
            $module = $item['module'];
            $form = $item['form'];
            $formUrl = $item['form_url'];
            $formMenu = $item['form_menu'];
            $section = $item['section'];
            $fieldName = $item['field_name'];
            $fieldLabel = $item['field_label'];
            $type = $item['type'] ?? 'dynamic_master'; // dynamic_master | static_options | dynamic_ajax

            // Build clear, authoritative description
            $lines = [];
            $lines[] = "### Form Field Data Lineage: {$fieldLabel} Select Box ({$form} - {$section})";
            $lines[] = "- **Target Screen & Form**: `{$form}` (URL: `{$formUrl}`, Menu: `{$formMenu}`)";
            $lines[] = "- **Form Section**: {$section}";
            $lines[] = "- **Field Identifier**: `{$fieldName}` (Label: `{$fieldLabel}`)";

            if ($type === 'dynamic_master' || $type === 'dynamic_ajax') {
                $sourceMenu = $item['source_menu'];
                $sourcePage = $item['source_page'];
                $sourceUrl = $item['source_url'];
                $sourceAddUrl = $item['source_add_url'] ?? ($sourceUrl . '/add');
                $sourceModel = $item['source_model'] ?? null;
                $sourceTable = $item['source_table'] ?? null;
                $entityName = $item['entity_name'] ?? $fieldLabel;
                $filterNotes = $item['filter_notes'] ?? null;

                $lines[] = "- **Where Data Comes From**: This data comes from **{$sourceMenu}** -> **{$sourcePage}** page (Direct URL: `{$sourceUrl}`).";
                if ($sourceModel && $sourceTable) {
                    $lines[] = "- **Underlying Eloquent Model & Table**: `App\\Models\\{$sourceModel}` (Database table: `{$sourceTable}`).";
                }
                if ($filterNotes) {
                    $lines[] = "- **Filtering / Dependency Behavior**: {$filterNotes}";
                }
                $lines[] = "- **How to Add New Options / Data**: If you need to add {$entityName}, you can go to **{$sourceMenu}** (`{$sourceUrl}`), click the **Add** button (or navigate to `{$sourceAddUrl}`), and enter the needed data.";
                $lines[] = "- **Direct Answer Summary**: This data comes from {$sourceMenu} -> {$sourcePage} page. If you add {$entityName}, you can go to {$sourcePage} page click Add button and add the needed data.";
            } else {
                // Static options
                $optionsList = implode(', ', $item['static_options'] ?? []);
                $lines[] = "- **Where Data Comes From**: Predefined static options defined within the ERP application form code.";
                $lines[] = "- **Available Options**: {$optionsList}";
                $lines[] = "- **Master Table Status**: This field has predefined choices within the Nachias ERP system and does not come from a separate master page.";
                $lines[] = "- **Direct Answer Summary**: This select box uses predefined system options ({$optionsList}) configured in the Nachias ERP form.";
            }

            $content = implode("\n", $lines);

            // Keywords for rich search matching
            $keywords = [
                $module,
                $form,
                $section,
                $fieldName,
                $fieldLabel,
                strtolower($fieldLabel) . ' select box',
                strtolower($fieldLabel) . ' dropdown',
                strtolower($fieldLabel) . ' data comes from',
                'where ' . strtolower($fieldLabel) . ' comes from',
                'where does ' . strtolower($fieldLabel) . ' come from',
                'how to add ' . strtolower($fieldLabel),
                'add ' . strtolower($fieldLabel),
                $formUrl,
                $formMenu,
            ];

            if (!empty($item['source_page'])) {
                $keywords[] = $item['source_page'];
                $keywords[] = $item['source_menu'];
                $keywords[] = $item['source_url'];
            }
            if (!empty($item['source_model'])) {
                $keywords[] = $item['source_model'];
            }
            if (!empty($item['aliases'])) {
                $keywords = array_merge($keywords, $item['aliases']);
            }

            $keywordStr = strtolower(implode(', ', array_unique(array_filter($keywords))));

            $title = "Field Data Source: {$fieldLabel} Select Box ({$form} - {$section})";

            $chunks[] = [
                'source_type' => 'field_data_source',
                'module' => $module,
                'screen' => $form,
                'title' => $title,
                'keywords' => $keywordStr,
                'url' => $formUrl,
                'menu_path' => $formMenu,
                'content' => $content,
                'meta' => [
                    'module' => $module,
                    'form' => $form,
                    'form_url' => $formUrl,
                    'form_menu' => $formMenu,
                    'section' => $section,
                    'field_name' => $fieldName,
                    'field_label' => $fieldLabel,
                    'type' => $type,
                    'source_menu' => $item['source_menu'] ?? null,
                    'source_page' => $item['source_page'] ?? null,
                    'source_url' => $item['source_url'] ?? null,
                    'source_add_url' => $item['source_add_url'] ?? null,
                    'source_model' => $item['source_model'] ?? null,
                    'source_table' => $item['source_table'] ?? null,
                ],
            ];
        }

        return $chunks;
    }

    /**
     * Complete, verified registry of all select boxes across all forms in Nachias ERP.
     */
    protected function getLineageDefinitions(): array
    {
        return [
            // =========================================================================
            // 1. PURCHASE MODULE -> PURCHASE ORDERS -> ADD PURCHASE FORM
            // =========================================================================
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'style_id',
                'field_label' => 'Style',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Styles',
                'source_page' => 'Styles',
                'source_url' => '/styles',
                'source_add_url' => '/styles/add',
                'source_model' => 'Style',
                'source_table' => 'styles',
                'entity_name' => 'style',
                'aliases' => ['style select box', 'style dropdown', 'purchase order style', 'po style', 'item details style'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'store_category_id',
                'field_label' => 'Store Category',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Store Category',
                'source_page' => 'Store Category',
                'source_url' => '/store_categories',
                'source_add_url' => '/store_categories/add',
                'source_model' => 'StoreCategory',
                'source_table' => 'store_categories',
                'entity_name' => 'store category',
                'aliases' => ['store category select box', 'store category dropdown', 'item details store category', 'po store category'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'raw_material_id',
                'field_label' => 'Raw Material',
                'type' => 'dynamic_ajax',
                'source_menu' => 'Master > Item Setup > Raw Materials',
                'source_page' => 'Raw Materials',
                'source_url' => '/raw_materials',
                'source_add_url' => '/raw_materials/add',
                'source_model' => 'RawMaterial',
                'source_table' => 'raw_materials',
                'entity_name' => 'raw material',
                'filter_notes' => 'Filtered dynamically via AJAX based on the selected Store Category.',
                'aliases' => ['raw material select box', 'raw material dropdown', 'item details raw material', 'po raw material'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'fabric_width_id',
                'field_label' => 'Fabric Width / Size',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Fabric Size (Width)',
                'source_page' => 'Fabric Size (Width)',
                'source_url' => '/fabric-sizes',
                'source_add_url' => '/fabric-sizes/add',
                'source_model' => 'FabricSize',
                'source_table' => 'fabric_sizes',
                'entity_name' => 'fabric width / size',
                'aliases' => ['fabric width select box', 'width select box', 'fabric size dropdown', 'po width'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'fabric_type_id',
                'field_label' => 'Fabric Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Fabric Type',
                'source_page' => 'Fabric Type',
                'source_url' => '/fabric_type',
                'source_add_url' => '/fabric_type/add',
                'source_model' => 'FabricType',
                'source_table' => 'fabric_types',
                'entity_name' => 'fabric type',
                'aliases' => ['fabric type select box', 'fabric type dropdown', 'po fabric type'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'color_id',
                'field_label' => 'Color',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Colors',
                'source_page' => 'Colors',
                'source_url' => '/colors',
                'source_add_url' => '/colors/add',
                'source_model' => 'Color',
                'source_table' => 'colors',
                'entity_name' => 'color',
                'aliases' => ['color select box', 'color dropdown', 'po color', 'item details color'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'brand_id',
                'field_label' => 'Brand',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Brands',
                'source_page' => 'Brands',
                'source_url' => '/brands',
                'source_add_url' => '/brands/add',
                'source_model' => 'Brand',
                'source_table' => 'brands',
                'entity_name' => 'brand',
                'aliases' => ['brand select box', 'brand dropdown', 'po brand'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'Item Details',
                'field_name' => 'uom_id',
                'field_label' => 'UOM',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > UOM',
                'source_page' => 'UOM',
                'source_url' => '/uoms',
                'source_add_url' => '/uoms/add',
                'source_model' => 'Uom',
                'source_table' => 'uoms',
                'entity_name' => 'UOM (Unit of Measurement)',
                'aliases' => ['uom select box', 'uom dropdown', 'unit of measurement', 'po uom'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'General Information',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Suppliers',
                'source_page' => 'Suppliers',
                'source_url' => '/suppliers',
                'source_add_url' => '/suppliers/add',
                'source_model' => 'Supplier',
                'source_table' => 'suppliers',
                'entity_name' => 'supplier',
                'aliases' => ['supplier select box', 'supplier dropdown', 'po supplier', 'purchase order supplier'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'General Information',
                'field_name' => 'purchase_commission_agent_id',
                'field_label' => 'Purchase Commission Agent',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Purchase Commission Agent',
                'source_page' => 'Purchase Commission Agent',
                'source_url' => '/purchase_commission_agent',
                'source_add_url' => '/purchase_commission_agent/add',
                'source_model' => 'PurchaseCommissionAgent',
                'source_table' => 'purchase_commission_agents',
                'entity_name' => 'purchase commission agent',
                'aliases' => ['commission agent select box', 'agent dropdown', 'po agent'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'General Information',
                'field_name' => 'store_type_id',
                'field_label' => 'Store Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Store Category',
                'source_page' => 'Store Category',
                'source_url' => '/store_categories',
                'source_add_url' => '/store_categories/add',
                'source_model' => 'StoreType',
                'source_table' => 'store_types',
                'entity_name' => 'store type',
                'aliases' => ['store type select box', 'store type dropdown', 'po store type'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'General Information',
                'field_name' => 'order_type',
                'field_label' => 'Order Type',
                'type' => 'static_options',
                'static_options' => ['Core Order', 'Repeat Order', 'New Order', 'Sample Order', 'Urgent Order'],
                'aliases' => ['order type select box', 'order type dropdown', 'po order type'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Order',
                'form_url' => '/purchase_orders/add',
                'form_menu' => 'Purchase > Purchase Orders',
                'section' => 'General Information',
                'field_name' => 'status',
                'field_label' => 'Status',
                'type' => 'static_options',
                'static_options' => ['Draft', 'Approved', 'Dispatched', 'Received'],
                'aliases' => ['po status select box', 'po status dropdown', 'purchase order status'],
            ],

            // =========================================================================
            // 2. PURCHASE MODULE -> PURCHASE INVOICES -> ADD PURCHASE INVOICE FORM
            // =========================================================================
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Invoice',
                'form_url' => '/purchase_invoices/add',
                'form_menu' => 'Purchase > Purchase Invoices',
                'section' => 'General Information',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Suppliers',
                'source_page' => 'Suppliers',
                'source_url' => '/suppliers',
                'source_add_url' => '/suppliers/add',
                'source_model' => 'Supplier',
                'source_table' => 'suppliers',
                'entity_name' => 'supplier',
                'aliases' => ['purchase invoice supplier select box', 'pi supplier'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Invoice',
                'form_url' => '/purchase_invoices/add',
                'form_menu' => 'Purchase > Purchase Invoices',
                'section' => 'General Information',
                'field_name' => 'purchase_order_id',
                'field_label' => 'Purchase Order',
                'type' => 'dynamic_master',
                'source_menu' => 'Purchase > Purchase Orders',
                'source_page' => 'Purchase Orders',
                'source_url' => '/purchase_orders',
                'source_add_url' => '/purchase_orders/add',
                'source_model' => 'PurchaseOrder',
                'source_table' => 'purchase_orders',
                'entity_name' => 'purchase order',
                'aliases' => ['purchase invoice po select box', 'purchase invoice po dropdown', 'pi po'],
            ],
            [
                'module' => 'Purchase',
                'form' => 'Add Purchase Invoice',
                'form_url' => '/purchase_invoices/add',
                'form_menu' => 'Purchase > Purchase Invoices',
                'section' => 'Charges',
                'field_name' => 'charge_id',
                'field_label' => 'Charge',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Charges',
                'source_page' => 'Charges',
                'source_url' => '/charges',
                'source_add_url' => '/charges/add',
                'source_model' => 'Charge',
                'source_table' => 'charges',
                'entity_name' => 'charge',
                'aliases' => ['purchase invoice charge select box', 'pi charge dropdown'],
            ],

            // =========================================================================
            // 3. SALES MODULE -> SALES ORDERS -> ADD SALES ORDER FORM
            // =========================================================================
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Customer Details',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Customers',
                'source_page' => 'Customers',
                'source_url' => '/customers',
                'source_add_url' => '/customers/add',
                'source_model' => 'Customer',
                'source_table' => 'customers',
                'entity_name' => 'customer',
                'aliases' => ['sales order customer select box', 'so customer dropdown', 'customer select box'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'General Information',
                'field_name' => 'season_id',
                'field_label' => 'Season',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Seasons',
                'source_page' => 'Seasons',
                'source_url' => '/seasons',
                'source_add_url' => '/seasons/add',
                'source_model' => 'Season',
                'source_table' => 'seasons',
                'entity_name' => 'season',
                'aliases' => ['sales order season select box', 'so season dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'General Information',
                'field_name' => 'store_id',
                'field_label' => 'Store',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Stores',
                'source_page' => 'Stores',
                'source_url' => '/stores',
                'source_add_url' => '/stores/add',
                'source_model' => 'Store',
                'source_table' => 'stores',
                'entity_name' => 'store',
                'aliases' => ['sales order store select box', 'so store dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'General Information',
                'field_name' => 'sales_agent_id',
                'field_label' => 'Sales Agent',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Sales Agents',
                'source_page' => 'Sales Agents',
                'source_url' => '/sales_agents',
                'source_add_url' => '/sales_agents/add',
                'source_model' => 'SalesAgent',
                'source_table' => 'sales_agents',
                'entity_name' => 'sales agent',
                'aliases' => ['sales order sales agent select box', 'so agent dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'General Information',
                'field_name' => 'zone_id',
                'field_label' => 'Zone',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Zones',
                'source_page' => 'Zones',
                'source_url' => '/zones',
                'source_add_url' => '/zones/add',
                'source_model' => 'Zone',
                'source_table' => 'zones',
                'entity_name' => 'zone',
                'aliases' => ['sales order zone select box', 'so zone dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Logistics & Shipping',
                'field_name' => 'shipping_method_id',
                'field_label' => 'Shipping Method',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Logistics Master > Shipping Methods',
                'source_page' => 'Shipping Methods',
                'source_url' => '/shipping_methods',
                'source_add_url' => '/shipping_methods/add',
                'source_model' => 'ShippingMethod',
                'source_table' => 'shipping_methods',
                'entity_name' => 'shipping method',
                'aliases' => ['shipping method select box', 'shipping method dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Logistics & Shipping',
                'field_name' => 'transport_mode_id',
                'field_label' => 'Transport Mode',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Logistics Master > Transport Mode',
                'source_page' => 'Transport Mode',
                'source_url' => '/transport_modes',
                'source_add_url' => '/transport_modes/add',
                'source_model' => 'TransportMode',
                'source_table' => 'transport_modes',
                'entity_name' => 'transport mode',
                'aliases' => ['transport mode select box', 'transport mode dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'General Information',
                'field_name' => 'service_provider_id',
                'field_label' => 'Service Provider / Plant',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Service Providers',
                'source_page' => 'Service Providers',
                'source_url' => '/service_providers',
                'source_add_url' => '/service_providers/add',
                'source_model' => 'ServiceProvider',
                'source_table' => 'service_providers',
                'entity_name' => 'service provider / plant',
                'aliases' => ['so plant select box', 'so service provider dropdown'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Item Details',
                'field_name' => 'color_id',
                'field_label' => 'Color',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Colors',
                'source_page' => 'Colors',
                'source_url' => '/colors',
                'source_add_url' => '/colors/add',
                'source_model' => 'Color',
                'source_table' => 'colors',
                'entity_name' => 'color',
                'aliases' => ['so color select box', 'sales order color'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Item Details',
                'field_name' => 'uom_id',
                'field_label' => 'UOM',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > UOM',
                'source_page' => 'UOM',
                'source_url' => '/uoms',
                'source_add_url' => '/uoms/add',
                'source_model' => 'Uom',
                'source_table' => 'uoms',
                'entity_name' => 'UOM',
                'aliases' => ['so uom select box', 'sales order uom'],
            ],
            [
                'module' => 'Sales',
                'form' => 'Add Sales Order',
                'form_url' => '/sales_orders/add',
                'form_menu' => 'Sales > Sales Orders',
                'section' => 'Charges',
                'field_name' => 'charge_id',
                'field_label' => 'Charge',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Charges',
                'source_page' => 'Charges',
                'source_url' => '/charges',
                'source_add_url' => '/charges/add',
                'source_model' => 'Charge',
                'source_table' => 'charges',
                'entity_name' => 'charge',
                'aliases' => ['so charge select box', 'sales order charge'],
            ],

            // =========================================================================
            // 4. PRODUCTION MODULE -> JOB CARD ENTRY -> ADD JOB CARD FORM
            // =========================================================================
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'brand_id',
                'field_label' => 'Brand',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Brands',
                'source_page' => 'Brands',
                'source_url' => '/brands',
                'source_add_url' => '/brands/add',
                'source_model' => 'Brand',
                'source_table' => 'brands',
                'entity_name' => 'brand',
                'aliases' => ['job card brand select box', 'jc brand dropdown', 'job card brand'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'season_id',
                'field_label' => 'Season',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Seasons',
                'source_page' => 'Seasons',
                'source_url' => '/seasons',
                'source_add_url' => '/seasons/add',
                'source_model' => 'Season',
                'source_table' => 'seasons',
                'entity_name' => 'season',
                'aliases' => ['job card season select box', 'jc season dropdown', 'job card season'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'process_group_id',
                'field_label' => 'Process Group',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Process Group',
                'source_page' => 'Process Group',
                'source_url' => '/process_groups',
                'source_add_url' => '/process_groups/add',
                'source_model' => 'ProcessGroup',
                'source_table' => 'process_groups',
                'entity_name' => 'process group',
                'aliases' => ['job card process group select box', 'jc process group dropdown', 'process group'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'size_ratio_id',
                'field_label' => 'Size & Ratio',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Size & Ratio',
                'source_page' => 'Size & Ratio',
                'source_url' => '/size_ratio',
                'source_add_url' => '/size_ratio/add',
                'source_model' => 'SizeRatio',
                'source_table' => 'size_ratios',
                'entity_name' => 'size and ratio',
                'aliases' => ['job card size ratio select box', 'jc size ratio dropdown', 'size ratio'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'service_provider_id',
                'field_label' => 'Plant / Service Provider',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Service Providers',
                'source_page' => 'Service Providers',
                'source_url' => '/service_providers',
                'source_add_url' => '/service_providers/add',
                'source_model' => 'ServiceProvider',
                'source_table' => 'service_providers',
                'entity_name' => 'plant / service provider',
                'aliases' => ['job card plant select box', 'jc plant dropdown', 'jc service provider'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'General Information',
                'field_name' => 'cutting_master_id',
                'field_label' => 'Cutting Master / Employee',
                'type' => 'dynamic_master',
                'source_menu' => 'Employees > Employees',
                'source_page' => 'Employees',
                'source_url' => '/employees',
                'source_add_url' => '/employees/add',
                'source_model' => 'User',
                'source_table' => 'users',
                'entity_name' => 'employee / cutting master',
                'aliases' => ['cutting master select box', 'jc cutting master dropdown', 'job card employee'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'fit_id',
                'field_label' => 'Fit',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Fits',
                'source_page' => 'Fits',
                'source_url' => '/fits',
                'source_add_url' => '/fits/add',
                'source_model' => 'Fit',
                'source_table' => 'fits',
                'entity_name' => 'fit',
                'aliases' => ['job card fit select box', 'fit dropdown', 'tailoring fit'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'patti_type_id',
                'field_label' => 'Patti Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Patti Types',
                'source_page' => 'Patti Types',
                'source_url' => '/patti_types',
                'source_add_url' => '/patti_types/add',
                'source_model' => 'PattiType',
                'source_table' => 'patti_types',
                'entity_name' => 'patti type',
                'aliases' => ['job card patti type select box', 'patti type dropdown'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'collar_type_id',
                'field_label' => 'Collar Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Collar Types',
                'source_page' => 'Collar Types',
                'source_url' => '/collar_types',
                'source_add_url' => '/collar_types/add',
                'source_model' => 'CollarType',
                'source_table' => 'collar_types',
                'entity_name' => 'collar type',
                'aliases' => ['job card collar type select box', 'collar type dropdown'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'cuff_type_id',
                'field_label' => 'Cuff Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Cuff Types',
                'source_page' => 'Cuff Types',
                'source_url' => '/cuff_types',
                'source_add_url' => '/cuff_types/add',
                'source_model' => 'CuffType',
                'source_table' => 'cuff_types',
                'entity_name' => 'cuff type',
                'aliases' => ['job card cuff type select box', 'cuff type dropdown'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'pocket_type_id',
                'field_label' => 'Pocket Type',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Pocket Types',
                'source_page' => 'Pocket Types',
                'source_url' => '/pocket_types',
                'source_add_url' => '/pocket_types/add',
                'source_model' => 'PocketType',
                'source_table' => 'pocket_types',
                'entity_name' => 'pocket type',
                'aliases' => ['job card pocket type select box', 'pocket type dropdown'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Tailoring Specifications',
                'field_name' => 'bottom_cut_id',
                'field_label' => 'Bottom Cut',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Tailoring Specification > Bottom Cuts',
                'source_page' => 'Bottom Cuts',
                'source_url' => '/bottom_cuts',
                'source_add_url' => '/bottom_cuts/add',
                'source_model' => 'BottomCut',
                'source_table' => 'bottom_cuts',
                'entity_name' => 'bottom cut',
                'aliases' => ['job card bottom cut select box', 'bottom cut dropdown'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Fabric Details',
                'field_name' => 'purchase_order_id',
                'field_label' => 'Purchase Order',
                'type' => 'dynamic_master',
                'source_menu' => 'Purchase > Purchase Orders',
                'source_page' => 'Purchase Orders',
                'source_url' => '/purchase_orders',
                'source_add_url' => '/purchase_orders/add',
                'source_model' => 'PurchaseOrder',
                'source_table' => 'purchase_orders',
                'entity_name' => 'purchase order',
                'aliases' => ['job card po select box', 'fabric details po'],
            ],
            [
                'module' => 'Production',
                'form' => 'Add Job Card Entry',
                'form_url' => '/job_card_entries/add',
                'form_menu' => 'Production > Job Card Entry',
                'section' => 'Production Stages',
                'field_name' => 'stage_id',
                'field_label' => 'Operation Stage',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Operation Stages',
                'source_page' => 'Operation Stages',
                'source_url' => '/operation_stages',
                'source_add_url' => '/operation_stages/add',
                'source_model' => 'OperationStage',
                'source_table' => 'operation_stages',
                'entity_name' => 'operation stage',
                'aliases' => ['production stage select box', 'operation stage dropdown', 'job card stage'],
            ],

            // =========================================================================
            // 5. STORE MODULE -> GRN ENTRY -> ADD GRN FORM
            // =========================================================================
            [
                'module' => 'Store',
                'form' => 'Add GRN Entry',
                'form_url' => '/grn_entries/add',
                'form_menu' => 'Store > GRN Entry',
                'section' => 'General Information',
                'field_name' => 'purchase_invoice_id',
                'field_label' => 'Purchase Invoice',
                'type' => 'dynamic_master',
                'source_menu' => 'Purchase > Purchase Invoices',
                'source_page' => 'Purchase Invoices',
                'source_url' => '/purchase_invoices',
                'source_add_url' => '/purchase_invoices/add',
                'source_model' => 'PurchaseInvoice',
                'source_table' => 'purchase_invoices',
                'entity_name' => 'purchase invoice',
                'aliases' => ['grn purchase invoice select box', 'grn invoice dropdown', 'grn pi'],
            ],
            [
                'module' => 'Store',
                'form' => 'Add GRN Entry',
                'form_url' => '/grn_entries/add',
                'form_menu' => 'Store > GRN Entry',
                'section' => 'Item Details',
                'field_name' => 'store_location_id',
                'field_label' => 'Store Location',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Warehouse Master > Store Location',
                'source_page' => 'Store Location',
                'source_url' => '/store_location',
                'source_add_url' => '/store_location/add',
                'source_model' => 'StoreLocation',
                'source_table' => 'store_locations',
                'entity_name' => 'store location',
                'aliases' => ['grn store location select box', 'store location dropdown', 'grn location'],
            ],

            // =========================================================================
            // 6. STORE MODULE -> STOCK ENTRY -> ADD STOCK ENTRY FORM
            // =========================================================================
            [
                'module' => 'Store',
                'form' => 'Add Stock Entry',
                'form_url' => '/stock_entries/add',
                'form_menu' => 'Store > Stock Entry',
                'section' => 'General Information',
                'field_name' => 'grn_entry_id',
                'field_label' => 'GRN Entry',
                'type' => 'dynamic_master',
                'source_menu' => 'Store > GRN Entry',
                'source_page' => 'GRN Entry',
                'source_url' => '/grn_entries',
                'source_add_url' => '/grn_entries/add',
                'source_model' => 'GrnEntry',
                'source_table' => 'grn_entries',
                'entity_name' => 'GRN entry',
                'aliases' => ['stock entry grn select box', 'stock entry grn dropdown'],
            ],
            [
                'module' => 'Store',
                'form' => 'Add Stock Entry',
                'form_url' => '/stock_entries/add',
                'form_menu' => 'Store > Stock Entry',
                'section' => 'General Information',
                'field_name' => 'warehouse_id',
                'field_label' => 'Warehouse',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Warehouse Master > Warehouse',
                'source_page' => 'Warehouse',
                'source_url' => '/warehouses',
                'source_add_url' => '/warehouse/add',
                'source_model' => 'Warehouse',
                'source_table' => 'warehouses',
                'entity_name' => 'warehouse',
                'aliases' => ['stock entry warehouse select box', 'warehouse dropdown'],
            ],
            [
                'module' => 'Store',
                'form' => 'Add Stock Entry',
                'form_url' => '/stock_entries/add',
                'form_menu' => 'Store > Stock Entry',
                'section' => 'Item Details',
                'field_name' => 'store_location_id',
                'field_label' => 'Store Location',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Warehouse Master > Store Location',
                'source_page' => 'Store Location',
                'source_url' => '/store_location',
                'source_add_url' => '/store_location/add',
                'source_model' => 'StoreLocation',
                'source_table' => 'store_locations',
                'entity_name' => 'store location',
                'aliases' => ['stock entry location select box', 'stock location dropdown'],
            ],

            // =========================================================================
            // 7. EMPLOYEES MODULE -> EMPLOYEES -> ADD EMPLOYEE FORM
            // =========================================================================
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Work Information',
                'field_name' => 'department_id',
                'field_label' => 'Department',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Departments',
                'source_page' => 'Departments',
                'source_url' => '/departments',
                'source_add_url' => '/departments/add',
                'source_model' => 'Department',
                'source_table' => 'departments',
                'entity_name' => 'department',
                'aliases' => ['employee department select box', 'department dropdown', 'staff department'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Work Information',
                'field_name' => 'role_id',
                'field_label' => 'Role',
                'type' => 'dynamic_master',
                'source_menu' => 'Employees > Roles',
                'source_page' => 'Roles',
                'source_url' => '/roles',
                'source_add_url' => '/roles/add',
                'source_model' => 'Role',
                'source_table' => 'roles',
                'entity_name' => 'role',
                'aliases' => ['employee role select box', 'role dropdown', 'staff role'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Personal Information',
                'field_name' => 'state_id',
                'field_label' => 'State',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > States',
                'source_page' => 'States',
                'source_url' => '/states',
                'source_add_url' => '/states/add',
                'source_model' => 'State',
                'source_table' => 'states',
                'entity_name' => 'state',
                'aliases' => ['employee state select box', 'state dropdown'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Personal Information',
                'field_name' => 'city_id',
                'field_label' => 'City',
                'type' => 'dynamic_ajax',
                'source_menu' => 'Master > Cities',
                'source_page' => 'Cities',
                'source_url' => '/cities',
                'source_add_url' => '/cities/add',
                'source_model' => 'City',
                'source_table' => 'cities',
                'entity_name' => 'city',
                'filter_notes' => 'Filtered dynamically via AJAX based on the selected State.',
                'aliases' => ['employee city select box', 'city dropdown'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Work Information',
                'field_name' => 'service_provider_id',
                'field_label' => 'Plant / Service Provider',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Service Providers',
                'source_page' => 'Service Providers',
                'source_url' => '/service_providers',
                'source_add_url' => '/service_providers/add',
                'source_model' => 'ServiceProvider',
                'source_table' => 'service_providers',
                'entity_name' => 'service provider / plant',
                'aliases' => ['employee plant select box', 'employee service provider'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Work Information',
                'field_name' => 'operation_stage_id',
                'field_label' => 'Operation Stage',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Operation Stages',
                'source_page' => 'Operation Stages',
                'source_url' => '/operation_stages',
                'source_add_url' => '/operation_stages/add',
                'source_model' => 'OperationStage',
                'source_table' => 'operation_stages',
                'entity_name' => 'operation stage',
                'aliases' => ['employee stage select box', 'employee operation stage'],
            ],
            [
                'module' => 'Employees',
                'form' => 'Add Employee',
                'form_url' => '/employees/add',
                'form_menu' => 'Employees > Employees',
                'section' => 'Work Information',
                'field_name' => 'device_id',
                'field_label' => 'Device',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Devices',
                'source_page' => 'Devices',
                'source_url' => '/devices',
                'source_add_url' => '/devices/add',
                'source_model' => 'Device',
                'source_table' => 'devices',
                'entity_name' => 'biometric / attendance device',
                'aliases' => ['employee device select box', 'device dropdown'],
            ],

            // =========================================================================
            // 8. MASTER MODULE -> ITEMS -> ADD ITEM FORM
            // =========================================================================
            [
                'module' => 'Master',
                'form' => 'Add Item',
                'form_url' => '/items/add',
                'form_menu' => 'Master > Item Setup > Items',
                'section' => 'General Information',
                'field_name' => 'brand_category_id',
                'field_label' => 'Brand Category',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Brand Category',
                'source_page' => 'Brand Category',
                'source_url' => '/brand_categories',
                'source_add_url' => '/brand_categories/add',
                'source_model' => 'BrandCategory',
                'source_table' => 'brand_categories',
                'entity_name' => 'brand category',
                'aliases' => ['item brand category select box', 'item brand category dropdown'],
            ],
            [
                'module' => 'Master',
                'form' => 'Add Item',
                'form_url' => '/items/add',
                'form_menu' => 'Master > Item Setup > Items',
                'section' => 'General Information',
                'field_name' => 'brand_id',
                'field_label' => 'Brand',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Item Setup > Brands',
                'source_page' => 'Brands',
                'source_url' => '/brands',
                'source_add_url' => '/brands/add',
                'source_model' => 'Brand',
                'source_table' => 'brands',
                'entity_name' => 'brand',
                'aliases' => ['item brand select box', 'item brand dropdown'],
            ],
            [
                'module' => 'Master',
                'form' => 'Add Item',
                'form_url' => '/items/add',
                'form_menu' => 'Master > Item Setup > Items',
                'section' => 'General Information',
                'field_name' => 'style_id',
                'field_label' => 'Style',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Styles',
                'source_page' => 'Styles',
                'source_url' => '/styles',
                'source_add_url' => '/styles/add',
                'source_model' => 'Style',
                'source_table' => 'styles',
                'entity_name' => 'style',
                'aliases' => ['item style select box', 'item style dropdown'],
            ],
            [
                'module' => 'Master',
                'form' => 'Add Item',
                'form_url' => '/items/add',
                'form_menu' => 'Master > Item Setup > Items',
                'section' => 'General Information',
                'field_name' => 'color_id',
                'field_label' => 'Color',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Colors',
                'source_page' => 'Colors',
                'source_url' => '/colors',
                'source_add_url' => '/colors/add',
                'source_model' => 'Color',
                'source_table' => 'colors',
                'entity_name' => 'color',
                'aliases' => ['item color select box', 'item color dropdown'],
            ],
            [
                'module' => 'Master',
                'form' => 'Add Item',
                'form_url' => '/items/add',
                'form_menu' => 'Master > Item Setup > Items',
                'section' => 'General Information',
                'field_name' => 'size_ratio_id',
                'field_label' => 'Size & Ratio',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Size & Ratio',
                'source_page' => 'Size & Ratio',
                'source_url' => '/size_ratio',
                'source_add_url' => '/size_ratio/add',
                'source_model' => 'SizeRatio',
                'source_table' => 'size_ratios',
                'entity_name' => 'size and ratio',
                'aliases' => ['item size ratio select box', 'item size ratio dropdown'],
            ],

            // =========================================================================
            // 9. MASTER MODULE -> PARTIES -> ADD CUSTOMER FORM
            // =========================================================================
            [
                'module' => 'Master',
                'form' => 'Add Customer',
                'form_url' => '/customers/add',
                'form_menu' => 'Master > Parties > Customers',
                'section' => 'General Information',
                'field_name' => 'zone_id',
                'field_label' => 'Zone',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Zones',
                'source_page' => 'Zones',
                'source_url' => '/zones',
                'source_add_url' => '/zones/add',
                'source_model' => 'Zone',
                'source_table' => 'zones',
                'entity_name' => 'zone',
                'aliases' => ['customer zone select box', 'customer zone dropdown'],
            ],
            [
                'module' => 'Master',
                'form' => 'Add Customer',
                'form_url' => '/customers/add',
                'form_menu' => 'Master > Parties > Customers',
                'section' => 'General Information',
                'field_name' => 'tax_id',
                'field_label' => 'Tax',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Taxes',
                'source_page' => 'Taxes',
                'source_url' => '/taxes',
                'source_add_url' => '/taxes/add',
                'source_model' => 'Tax',
                'source_table' => 'taxes',
                'entity_name' => 'tax',
                'aliases' => ['customer tax select box', 'customer tax dropdown'],
            ],

            // =========================================================================
            // 10. MASTER MODULE -> PARTIES -> ADD SUPPLIER FORM
            // =========================================================================
            [
                'module' => 'Master',
                'form' => 'Add Supplier',
                'form_url' => '/suppliers/add',
                'form_menu' => 'Master > Parties > Suppliers',
                'section' => 'General Information',
                'field_name' => 'purchase_commission_agent_id',
                'field_label' => 'Purchase Commission Agent',
                'type' => 'dynamic_master',
                'source_menu' => 'Master > Parties > Purchase Commission Agent',
                'source_page' => 'Purchase Commission Agent',
                'source_url' => '/purchase_commission_agent',
                'source_add_url' => '/purchase_commission_agent/add',
                'source_model' => 'PurchaseCommissionAgent',
                'source_table' => 'purchase_commission_agents',
                'entity_name' => 'purchase commission agent',
                'aliases' => ['supplier commission agent select box', 'supplier agent dropdown'],
            ],

            // =========================================================================
            // 11. MANAGE PAYMENTS -> ADD PAYMENT FORM
            // =========================================================================
            [
                'module' => 'Manage Payments',
                'form' => 'Add Payment',
                'form_url' => '/payments/add',
                'form_menu' => 'Manage Payments',
                'section' => 'Payment Details',
                'field_name' => 'payment_type',
                'field_label' => 'Payment Type',
                'type' => 'static_options',
                'static_options' => ['Customer Collection', 'Supplier Payment', 'Agent Commission'],
                'aliases' => ['payment type select box', 'payment type dropdown', 'payment type'],
            ],
            [
                'module' => 'Manage Payments',
                'form' => 'Add Payment',
                'form_url' => '/payments/add',
                'form_menu' => 'Manage Payments',
                'section' => 'Payment Details',
                'field_name' => 'payment_mode',
                'field_label' => 'Payment Mode',
                'type' => 'static_options',
                'static_options' => ['Cash', 'Bank (Cheque)', 'Online (UPI)', 'NEFT/RTGS'],
                'aliases' => ['payment mode select box', 'payment mode dropdown', 'payment mode'],
            ],

            // =========================================================================
            // 12. BILLING -> ADD BILLING FORM
            // =========================================================================
            [
                'module' => 'Billing',
                'form' => 'Add Billing',
                'form_url' => '/billing/add',
                'form_menu' => 'Billing',
                'section' => 'Billing Details',
                'field_name' => 'billing_type',
                'field_label' => 'Billing Type',
                'type' => 'static_options',
                'static_options' => ['Purchase', 'Sales', 'Service', 'Job Work', 'Transport'],
                'aliases' => ['billing type select box', 'billing type dropdown'],
            ],
            [
                'module' => 'Billing',
                'form' => 'Add Billing',
                'form_url' => '/billing/add',
                'form_menu' => 'Billing',
                'section' => 'Billing Details',
                'field_name' => 'status',
                'field_label' => 'Status',
                'type' => 'static_options',
                'static_options' => ['Pending', 'Partially Paid', 'Paid', 'Cancelled'],
                'aliases' => ['billing status select box', 'billing status dropdown'],
            ],
        ];
    }
}
